QAQCoder/JavaFX-Online-MusicPlayer-latest
https://github.com/QAQCoder/JavaFX-Online-MusicPlayer-latest
[latest-version] a simple javafx online music player
No License
2019-06-17T02:46:44
12



drallgood/jpasskit
https://github.com/drallgood/jpasskit
jPasskit is an Java™ implementation of the Apple™ PassKit Web Service.
Apache-2.0 license
2019-06-17T02:45:42
133



Zzzia/qiniuToken
https://github.com/Zzzia/qiniuToken
java服务器端七牛token获取工具
No License
2019-06-17T02:45:36
16



schemacrawler/SchemaCrawler
https://github.com/schemacrawler/SchemaCrawler
Free database schema discovery and comprehension tool
No License
2019-06-17T02:44:27
740



OpenBW/BWAPI4J
https://github.com/OpenBW/BWAPI4J
BWAPI wrapper for Java
LGPL-3.0 license
2019-06-17T02:43:23
24



sormuras/bach
https://github.com/sormuras/bach
Java Shell Builder - Use jshell/java to build your modular Java project
Apache-2.0 license
2019-06-17T02:38:56
75



zkoss/zk
https://github.com/zkoss/zk
ZK is a highly productive Java framework for building amazing enterprise web and mobile applications
No License
2019-06-17T02:37:49
282



0opslab/opslabJutil
https://github.com/0opslab/opslabJutil
Java utils
No License
2019-06-17T02:28:51
687



jxnu-liguobin/cs-summary-reflection
https://github.com/jxnu-liguobin/cs-summary-reflection
✏️ 📝 Recording Learning Interview Summary and Reflection
Apache-2.0 license
2019-06-17T02:25:20
447



AmazMod/AmazMod
https://github.com/AmazMod/AmazMod
Phone/Watch app that provides a new notification system along with other features for Amazfit Pace/Stratos/Verge watches
No License
2019-06-17T02:11:57
166



Snailclimb/JavaGuide
https://github.com/Snailclimb/JavaGuide
【Java学习+面试指南】 一份涵盖大部分Java程序员所需要掌握的核心知识。
No License
2019-06-17T02:09:29
44.8



TridentMC/MovingWorld
https://github.com/TridentMC/MovingWorld
A library for minecraft mods that want moving player made structures. Powered by false promises. Maintained by darkev…
Apache-2.0 license
2019-06-17T02:09:09
18



XerTheSquirrel/SquirrelJME
https://github.com/XerTheSquirrel/SquirrelJME
SquirrelJME intends to be a Java ME 8 compatible JVM (Embedded/J2ME) and desires to be ported to many systems (Deskto…
No License
2019-06-17T02:07:23
47



timandy/linq
https://github.com/timandy/linq
LINQ to Objects for Java.
No License
2019-06-17T02:02:07
35



apache/dubbo
https://github.com/apache/dubbo
Apache Dubbo is a high-performance, java based, open source RPC framework.
Apache-2.0 license
2019-06-17T01:59:08
27.2



seancfoley/IPAddress
https://github.com/seancfoley/IPAddress
Java library for handling IP addresses and subnets, both IPv4 and IPv6
Apache-2.0 license
2019-06-17T01:49:41
75



lessthanoptimal/BoofCV
https://github.com/lessthanoptimal/BoofCV
Fast computer vision library written entirely in Java.
Apache-2.0 license
2019-06-17T01:37:33
528



dddjava/Jig
https://github.com/dddjava/Jig
Java Instant-document Gazer
Apache-2.0 license
2019-06-17T01:34:15
59



palatable/lambda
https://github.com/palatable/lambda
Functional patterns for Java
MIT license
2019-06-17T01:33:44
562



gavenwangcn/vole
https://github.com/gavenwangcn/vole
SpringCloud Micro service business framework , SpringCloud 微服务商业脚手架
No License
2019-06-17T01:27:10
287



Subterranean-Security/Sandpolis
https://github.com/Subterranean-Security/Sandpolis
Ultimate remote management utility
Apache-2.0 license
2019-06-17T01:16:01
12



dragon66/icafe
https://github.com/dragon66/icafe
Java library for reading, writing, converting and manipulating images and metadata
EPL-1.0 license
2019-06-17T01:06:22
119



dragon66/icafe
https://github.com/dragon66/icafe
Java library for reading, writing, converting and manipulating images and metadata
EPL-1.0 license
2019-06-17T01:06:22
119



apache/incubator-datasketches-memory
https://github.com/apache/incubator-datasketches-memory
High performance native memory access for Java.
Apache-2.0 license
2019-06-17T01:01:50
67



apache/incubator-datasketches-memory
https://github.com/apache/incubator-datasketches-memory
High performance native memory access for Java.
Apache-2.0 license
2019-06-17T01:01:50
67



DenizenScript/Denizen-For-Bukkit
https://github.com/DenizenScript/Denizen-For-Bukkit
NPC and general Bukkit scripting!
MIT license
2019-06-17T00:58:40
72



oeuvres/Alix
https://github.com/oeuvres/Alix
Lemmatisation et plus pour le français (en java)
Apache-2.0 license
2019-06-17T00:45:04
11



